### ISSUE TITLE
🐛 BUG: `wrangler d1 execute` treats escaped semicolons as the start of a new statement

### ISSUE THREAD

**Issue by dcposch** [cloudflare/wrangler2#2366] opened 2022-12-08 18:29 UTC
### What version of `Wrangler` are you using?

2.6.1

### What operating system are you using?

Mac

### Steps to reproduce

- Create a SQL file with semicolons escaped inside a string literal.
- Run it with `wrangler d1 execute`

### Expected behavior

Works

### Actual behavior

```
✘ [ERROR] A request to the Cloudflare API (/accounts/09742c49bc8b4f681a71c115327b6e29/d1/database/8bc06ccd-7565-473d-b60b-aafa25d38e1f/query) failed.

  ERROR 9009: SQL prepare error: near "addition": syntax error in addition of an
  elevator at all three floors; at offset 0 [code: 7500]
```

digging in, the error message above came from the following statement

```
INSERT INTO projects VALUES('2014-000544','2468 39th Ave','2468 39TH AVE 94116','2014-000544PRJ','PRJ','Closed','2014-10-27','2017-04-10',0,'Hussein, Ahmed','','','','','','','Veritcal addition of a third floor; addition of an elevator at all three floors; 3 foot deep deck on 2nd and 3rd floors; 6'' deep staircase to the second and third floor at rear.','COMPLETE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
```

**Comment by xtuc** [comment] 2022-12-28 08:45
@dcposch  could you please try again and confirm the issue is fixed?

**Comment by rozenmd** [comment] 2022-12-28 10:51
Looks like this issue has been fixed via an internal patch to the D1 API - let me know if there are still problems and I'll reopen this issue

**Closed** 2022-12-28 16:51 UTC
Labels: bug, d1
