### ISSUE TITLE
Login fails due to CORS violation

### ISSUE THREAD

**Issue by MikeAshby** [cloudflare/wrangler2#978] opened 2022-05-12 16:44 UTC
The initial "getting started with" does not work. Users will experience "Error" in the  browser when attempting to login from command line: npx wrangler dev

**Comment by threepointone** [comment] 2022-05-12 17:04
Could you explain in detail what the issue is? Where did you see a CORS issue? Where did you see the "Error:"? Does it reproduce consistently? Any details would be helpful for us to investigate, thank you!

**Comment by threepointone** [comment] 2022-05-13 09:47
I believe this was a temporary issue, sometime our oauth page simply says "Error:" and nothing else. Opening up the browser devtools on this page logs a couple of CORS issues for a couple of assets, but that's not related to this problem.  logs a We'll follow up on that internally. I believe a retry would have fixed this. I'm going to close this issue, but let me know if you face any further issues.

**Closed by threepointone** 2022-05-13 09:47 UTC
