### ISSUE TITLE
🐛 BUG: wrangler generate: conflicting guidance

### ISSUE THREAD

**Issue by polybuildr** [cloudflare/wrangler2#1170] opened 2022-06-02 13:56 UTC
### What version of `Wrangler` are you using?

2.0.7

### What operating system are you using?

Linux/Ubuntu

### Describe the Bug

Hello! :wave: 

This is a ~~slight bit of a rant~~ "friction log" to show the steps I took getting started with wrangler and a couple of things that went wrong. I've filed this as a bug but I'm not sure that's the best type of issue here!

1. Read the guide on https://dash.cloudflare.com/<redacted>/workers/cli
2. Guide says "**Create your first project.** Generate a project using any of our Starters. You'll be set up with a Wrangler configuration file that you can quickly modify and publish." Below this is the command `wrangler init my-app`.
3. I run `wrangler init my-app`, assuming it will ask me which starter I'd like to initialize with.
4. wrangler just initializes a hello world example :worried:
5. I say: okay, sure, I'll go look at an example repository and see what it says.
6. I open https://github.com/cloudflare/worker-template-router which says I should use `wrangler generate`. I worry that this will not be compatible with an existing initialized repository, but I decide to go for it.
7. `wrangler generate myapp https://github.com/cloudflare/worker-template-router` errors (:worried:) with

>  `wrangler generate` has been deprecated.
>   Try running `wrangler init` to generate a basic Worker, or cloning the template repository
>   instead:
>   
>   ```
>   git clone https://github.com/cloudflare/worker-template-router
>   ```
>   
>   Please refer to https://developers.cloudflare.com/workers/wrangler/deprecations/#generate for more
>   information.
> 

8. I think: oh, okay. Not sure how I should have done this, but I'll go read that link.
9. https://developers.cloudflare.com/workers/wrangler/deprecations/#generate is a 404. :worried: 

I'm sure it will all work out in the end and I can work around this, just thought I'd let you all know so you could look into removing some of the friction when getting set up! Thanks! :grin:

**Comment by petebacondarwin** [comment] 2022-06-02 14:32
Actually this is basically a duplicate of https://github.com/cloudflare/wrangler2/issues/1084. So let's close this and continue the discussion there.

**Closed by petebacondarwin** 2022-06-02 14:32 UTC
Labels: bug
