### ISSUE TITLE
🐛 BUG: _headers file is not uploaded using `wrangler pages publish`

### ISSUE THREAD

**Issue by akosel** [cloudflare/wrangler2#1215] opened 2022-06-09 14:15 UTC
### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

Linux

### Describe the Bug

I started a [chat in the discord here](https://discord.com/channels/595317990191398933/799437470004412476/984457631483695124) for some added context/troubleshooting, but I'll summarize here as well.

In CircleCI, I am running `npx wrangler pages publish ./build --project-name=staging`. But when I check in the Cloudflare UI, the `_headers` file is not included in the list of deployed files.

The build directory has 207 files, but when running the command it indicates it is only uploading 206 files. The missing file is my `_headers` file. I ssh-ed into the CIrcleCI instance running the job and confirmed the `_headers` file is in the `build` directory. 

I looked through the [`pages.tsx`](https://github.com/cloudflare/wrangler2/blob/e64812e1dd38729959ff16abf2a8623543e25896/packages/wrangler/src/pages.tsx) file to try to understand what might be happening, but cannot make sense of the intended behavior. It does appear to be purposefully ignored to some degree, but also seems like it is POSTed in the form data of a request to Cloudflare. I assume someone with more familiarity with this code will have better luck.

Thank you!

**Comment by sidharthachatterjee** [comment] 2022-06-09 14:44
@akosel Hi there! What you're seeing is the intended behaviour. 

`_redirects` and `_headers` are POSTed to an endpoint for them to be added to the Pages deployment (and hence take effect) but they're not uploaded as static files since one typically doesn't want to _serve_ them. That's why they are ignored and not showing up in the deployed files list. 

You should however see them taking effect. If you don't, let me know and I'll investigate. Closing this in the mean time! Cheers.

**Closed by sidharthachatterjee** 2022-06-09 14:44 UTC
Labels: pages

**Comment by akosel** [comment] 2022-06-09 14:45
Ahh, ok, thank you for the quick response!
