### ISSUE TITLE
🐛 BUG: NO_D1_WARNING = true not working in wrangler.toml file

### ISSUE THREAD

**Issue by VR-Architect** [cloudflare/wrangler2#2423] opened 2022-12-16 17:44 UTC
### What version of `Wrangler` are you using?

2.6.1

### What operating system are you using?

Windows 10

### Describe the Bug

Wrangler file:
```
name = "login"
main = "src/index.ts"
compatibility_date = "2022-12-12"
NO_D1_WARNING = true

[[ d1_databases ]]
binding = "DB" 
database_name = "..."
database_id = "..."
```

wrangler publish output:
```
 ⛅️ wrangler 2.6.1 (update available 2.6.2)
-----------------------------------------------------
▲ [WARNING] Processing wrangler.toml configuration:

    - D1 Bindings are currently in alpha to allow the API to evolve before general availability.
      Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
      Note: set NO_D1_WARNING=true to hide this message
    - Unexpected fields found in top-level field: "NO_D1_WARNING"

Your worker has access to the following bindings:
- KV Namespaces:
  - KV_TOKENS: *
- D1 Databases:
  - DB: MyDB (*)
Total Upload: 53.68 KiB / gzip: 13.44 KiB
Uploaded login (1.47 sec)
Published login (0.26 sec)
  https://*.*.workers.dev
Current Deployment ID: aa5ee6d1-cecf-408f-9e77-60d69e89c640
```

**Comment by ben-xD** [comment] 2022-12-16 20:52
That's an environment variable, not a wrangler config.

Add to your `~/.zshrc` file:
```
# Cloudflare
export NO_D1_WARNING=true
```

Side note: the suggestion could be improved linguistically 😅.

**Comment by admah** [comment] 2022-12-21 17:17
@VR-Architect in addition to the suggestion from @ben-xD, you could set the var like: `NO_D1_WARNING=true npx wrangler...`

I'm going to close this issue as it's not a bug with Wrangler's functionality.

**Closed by admah** 2022-12-21 17:17 UTC
Labels: bug
