### ISSUE TITLE
🚀 Feature Request: NODE shim for Cloudflare Functions

### ISSUE THREAD

**Issue by Ucinorn** [cloudflare/wrangler2#1600] opened 2022-08-02 10:12 UTC
### Describe the solution

I'm currently playing around with Cloudflare Pages, with the hope that it's an all-in-one solution for small CRUD apps for my work backed by KV.

I hoped to use npm modules like imap and nodemailer in my functions, however when I initiate my workers locally I get errors saying that native node modules are not available. 

```
    [ERROR] Could not resolve "tls"

    functions/node_modules/imap/lib/Connection.js:1:18:
      1 │ var tls = require('tls'),
        ╵                   ~~~~~

     The package "tls" wasn't found on the file system but is built into node. Are you trying to bundle
     for node? You can use "platform: 'node'" to do that, which will remove this error.
```

I read that this issue is resolved in regular workers by adding node_compat = true to the wrangler.toml file [(see answer here)](https://github.com/cloudflare/wrangler2/issues/1047#issuecomment-1129736260) but config files are not available to the default Pages Functions setup. It works 'automagically' without a config file at all.  

I want to keep my application lean and use the file based routing of Functions, instead of ejecting to a single file and lose all that functionality. Is there a way to configure either my build command or the webpack build to shim all the default Node packages locally to replicate a Workers environment running on the edge?

**Comment by GregBrimble** [comment] 2022-08-09 08:14
Closed as dupe of #1074

**Closed by GregBrimble** 2022-08-09 08:14 UTC
Labels: enhancement, pages
