### ISSUE TITLE
🐛 BUG: Adding wrangler@alpha as a dependency breaks `react-scripts build` with a TS error

### ISSUE THREAD

**Issue by benallfree** [cloudflare/wrangler2#546] opened 2022-03-05 12:59 UTC
### What version of `Wrangler` are you using?

0.0.0-046b17d

### What operating system are you using?

Mac

### Describe the Bug

I just noticed that doing `yarn add -D wrangler@alpha` and then `react-scripts build` will cause the following error:

```
$ react-scripts build
Creating an optimized production build...
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.6.0

YOUR TYPESCRIPT VERSION: 4.6.2

Please only submit bug reports when using the officially supported version.

=============
Failed to compile.

TS2339: Property 'serviceWorker' does not exist on type 'WorkerNavigator'.
    44 |         // Add some additional logging to localhost, pointing developers to the
    45 |         // service worker/PWA documentation.
  > 46 |         navigator.serviceWorker.ready.then(() => {
       |                   ^^^^^^^^^^^^^
    47 |           console.log(
    48 |             'This web app is being served cache-first by a service ' +
    49 |               'worker. To learn more, visit https://cra.link/PWA'


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by threepointone** [comment] 2022-03-05 18:06
That's... weird. We'll have a look, but could you also make a repo that reproduces this error? Thank you!

**Comment by benallfree** [comment] 2022-03-05 22:39
Of course now I can't repro... did it 3 times last night! Should I close this until it resurfaces?

**Comment by benallfree** [comment] 2022-03-05 22:50
Ok wait, the latest commit 4b6c973 has fixed the problem. Here's a repro based on 046b17d which shows the problem. It might be good to be aware that something in 4b6c973 fixes this bug.

https://github.com/benallfree/wrangler-bug

**Comment by benallfree** [comment] 2022-03-05 22:52
Maybe something around here? https://github.com/cloudflare/wrangler2/commit/4b6c973dfdaf44429a47c8da387f9bc706ef4664#diff-5e47c8c5ec00bfdc010f06653422c5db6be55b5c61226212cf593b8c57098b6cR452

The problem was basically that TS was typing `navigator` as `WorkerNavigator` instead of `Navigator`.

**Comment by threepointone** [comment] 2022-03-06 06:39
Ok, I can guess what's going on here. `@cloudflare/workers-types` just dumps a bunch of globals which can clash with other globals (in this case, browser defaults). the  A proper fix here is to make the types from `@cloudflare/workers-types` be explicitly importable. Sorry for the frustration this has caused!

I'm going to close this and track it at https://github.com/cloudflare/workers-types/issues/195

**Closed** 2022-03-06 07:53 UTC
Labels: bug

**Comment by benallfree** [comment] 2022-03-06 09:38
Hmm I considered that possibility, but TS typically throws an error if two global type definitions conflict with each other. For example, I've seen that happen with multiple versions of `@types/react` being included by dependencies.

Here it seems more like `lib.webworker.d.ts` is being used instead of `lib.dom.d.ts`. Both define `navigator`, [here in lib.dom.d.ts](https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L18264) and [here in lib.webworker.d.ts](https://github.com/microsoft/TypeScript/blob/cec2fda9a53620dc545a2c4d7b0156446ab145b4/lib/lib.webworker.d.ts#L5864). 

I agree that exports for `@cloudflare/worker-types` is a good idea, but what change in 4b6c973 fixes things?

**Comment by threepointone** [comment] 2022-03-06 12:37
I really can't tell, tbh. Extremely weird. wrangler doesn't even bring along workers-types. It might be a deeper dependency that's misbehaving (but then again, I have no idea what fixed it in the newer version, since that didn't touch deps).

**Comment by petebacondarwin** [comment] 2022-03-07 09:54
I wonder if your original reproduction was using an older version of TS? And when you created a new repro, it just installed a version of TS that did not have this problem?

**Comment by petebacondarwin** [comment] 2022-03-07 13:48
Oh! I thought you couldn't reproduce it at all now. Let me try.

**Comment by benallfree** [comment] 2022-03-07 14:47
Ok now I can't repro it at all again. I think the first time I tested it was nested inside another project with parent `node_modules` folders. Perhaps something in that hierarchy was conflicting. Thanks anyway!
