### ISSUE TITLE
Wrangler pages dev server cannot proxy Next.JS webpack hot module replacement websocket connection 

### ISSUE THREAD

**Issue by cook1emonstr** [cloudflare/wrangler2#691] opened 2022-03-20 22:56 UTC
#### Describe the bug

The next.js dev server's webpack hot module replacement connection cannot be established through the wrangler pages dev proxy when using the automatic proxy command variant (ie `npx wrangler pages dev -- npx next dev`). Resulting in endless connection retries. 

Adding a proxy property to package.json did not resolve the issue.  

You can suppress the message by just building and exporting the next app (ie using `next build && next export && npx wrangler pages dev ./out`), but then you lose out on local dev features 

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Create a vanilla next.js project (you might need to create some /functions files for wrangler pages to work)
2. Run `npx wrangler pages dev -- npx next dev`
3. See repeating connection error to `ws://localhost:8788/_next/webpack-hmr`: 
```
Could not proxy request: TypeError: fetch failed 
GET /_next/webpack-hmr 502 Bad Gateway (1.63ms)
[pages:err] TypeError: Web Socket request did not return status 101 Switching Protocols response with Web Socket
    at Server.<anonymous> (C:\Users\andre\WebstormProjects\scalespace.app\node_modules\@miniflare\http-server\src\index.ts:383:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The connection establishes just fine when accessing the nextjs dev server directly (default url: `ws://localhost:3000/_next/webpack-hmr`)

#### Expected behavior

Hot module replacement connection establishes through wrangler pages dev proxy server upon app load for a more seamless development experience 

#### Environment and versions

Fill out the following information about your environment.

* operating system: Microsoft Windows 11 Pro 64-bit
* output of `wrangler -V`: 0.0.19 (wrangler@beta package)
* output of `node -v`: v16.13.0
* content of `wrangler.toml`: N\A

**Comment by GregBrimble** [comment] 2022-03-27 22:31
Dupe of #70.

**Comment by petebacondarwin** [comment] 2022-03-28 06:16
Closing as this is a duplicate. Thanks for reporting @cook1emonstr - let's continue the discussion at #70.

**Closed by petebacondarwin** 2022-03-28 06:16 UTC
Labels: bug, pages
