### ISSUE TITLE
🐛 BUG & 🌟 Feature : No Colored Logs in `wrangler2 dev` and `console.dir(object, { depth: null })` shows redacted output

### ISSUE THREAD

**Issue by touhidurrr** [cloudflare/wrangler2#590] opened 2022-03-14 11:20 UTC
### What version of `Wrangler` are you using?

0.0.19

### What operating system are you using?

Linux

### Describe the Bug

The logs in `wrangler2 dev` are so creepy and the behaviour is weird sometimes also. Things like:
```js
console.dir(object, { depth: null });
```
Doesn’t output full object. Also colors are missing.

**Comment by touhidurrr** [comment] 2022-03-14 11:20
Needs Feature Request Tag also

**Comment by petebacondarwin** [comment] 2022-05-30 10:44
Closing as a duplicate of #188

**Closed by petebacondarwin** 2022-05-30 10:44 UTC
Labels: enhancement
