### ISSUE TITLE
🐛 BUG: Content-Length header missing from worker response when Content-Type present

### ISSUE THREAD

**Issue by alukach** [cloudflare/wrangler2#1972] opened 2022-10-04 01:43 UTC
### What version of `Wrangler` are you using?

2.0.24

### What operating system are you using?

Mac

### Describe the Bug

When running `wrangler dev`, the `Content-Length` header is missing from responses if the `Content-Type` header is present and the `Content-Length` value is greater than `"47"`.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Create `src/index.ts`:
    ```ts
    // src/index.ts
    export default {
      async fetch(request: Request): Promise<Response> {
        const query = new URL(request.url).searchParams;
        const contentLength = query.get("length") || "0";
        const useContentType = !query.has("no-content-type");
    
        return new Response(null, {
          headers: {
            "content-length": contentLength,
            "content-type": useContentType ? "text/plain" : "",
          },
        });
      },
    };
    ```
1. Run:
    ```sh
    wrangler dev src/index.ts
    ```
1. Test headers:
    ```sh
    curl --head "http://localhost:8787?length=47" # Should see content-length & content-type header
    curl --head "http://localhost:8787?length=48" # Will see only see content-type header
    curl --head "http://localhost:8787?length=48&no-content-type" # Will only see content-length
    ```

<details>

<summary>Example responses</summary>

```sh
➤ curl --head "http://localhost:8787?length=47"
HTTP/1.1 200 OK
date: Tue, 04 Oct 2022 01:56:18 GMT
content-type: text/plain
content-length: 47
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=0DzkIHu1Lq67UVp%2F3C6xjrLmoYA8hemI0R8ljz3tvi7u9myGZ%2BVkt%2FdFIeM3WKpPafwGrEAgY7H3ruK4t91qmfhDYUYH1iwZ%2Bw3z4lIESO4fP276c61m8SpV81EwTLMJGWajRXlu0IvBudGEdrjDAnI0Vt9qSEDT7tNy9r9%2F4oBG"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
vary: Accept-Encoding
cf-ray: 754a4ce1befe8419-YVR
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
server: cloudflare
Connection: keep-alive
Keep-Alive: timeout=5

➤ curl --head "http://localhost:8787?length=48"
HTTP/1.1 200 OK
date: Tue, 04 Oct 2022 01:56:24 GMT
content-type: text/plain
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=SRSFjjRgbee0eBWHfBA7HRXPYIyWWuiXF7SjH493J7jfTz7OsdT6TskyZ%2BIR6u7F2o1Y3UtpHHKhYGnYFFEPH4bNv7JuOXQliDbRjDkfy0%2BC7KIamVJWlYB7aGXO4PxSLL24tcY1pD0RgawhKFOA%2B4Gf8SSFfrfTQgWIhWFo6MzX"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
vary: Accept-Encoding
cf-ray: 754a4d027d628419-YVR
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
server: cloudflare
Connection: keep-alive
Keep-Alive: timeout=5

➤ curl --head "http://localhost:8787?length=48&no-content-type"
HTTP/1.1 200 OK
date: Tue, 04 Oct 2022 01:56:33 GMT
content-length: 48
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=TFg3iX90nLT%2FuAJsytKW9Y1WjbxmomkByaoO1y6lHBTgxt8YReSIXFPdpg84SMuJgziKoGgGr4gDmosML9L6%2Ft3cq7vh%2BglfWpPs9p0q8xUJncc9VJ%2FOFjtSyYpu5PHoF%2B67Omh6rwB%2FMFsZZ9sWlnqNGB%2B0%2FGObC1rLfUD0i1L5"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
vary: Accept-Encoding
cf-ray: 754a4d3f8af18419-YVR
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
server: cloudflare
Connection: keep-alive
Keep-Alive: timeout=5
```

</details>

#### Work Around

As discovered in the [Cloudflare community forum](https://community.cloudflare.com/t/content-length-header-missing-when-content-type-present/423568/), this behaviour can be avoided by running `wrangler dev` with the `--local` flag (`wrangler dev --local`).

**Comment by penalosa** [comment] 2022-10-04 12:00
I can't seem to reproduce this. Running `npx wrangler@2.0.24 dev src/index.ts` and `curl --head "http://localhost:8787?length=48"` gives me:
```txt
HTTP/1.1 200 OK
date: Tue, 04 Oct 2022 11:57:05 GMT
content-type: text/plain
content-length: 48
Connection: keep-alive
Keep-Alive: timeout=5
```

Would you be able to create a GitHub repo that demonstrates this bug, complete with `wrangler.toml`, just to try and isolate where the issue is?

**Comment by alukach** [comment] 2022-10-04 17:34
@penalosa Thanks for the quick review.  I have created a repo demonstrating my issue here: https://github.com/alukach/cf-wrangler-bug-example

Looking at your example, I'm curious why your local responses aren't getting any of the Cloudflare headers (e.g. `cf-ray`).  Are you sure that you're not running that server in local mode?

**Comment by penalosa** [comment] 2022-10-06 00:36
Could you check if the behaviour is present in the latest version of wrangler (2.1.10)? It looks like that might solve the issue in your example repo (at least, it seems to for me). As to _why_ this happened in 2.0.24, I'm honestly baffled (I'll investigate a bit more), but hopefully the latest version fixes the issue.

**Comment by alukach** [comment] 2022-10-06 04:00
> It looks like that might solve the issue in your example repo (at least, it seems to for me).

Are you saying that you were able to reproduce the error with 2.0.24 and then you couldn't with 2.1.10?

On my system, I can confirm that the error continues with version `2.1.10`.

```
➤ curl --head "http://localhost:8787?length=48"
HTTP/1.1 200 OK
date: Thu, 06 Oct 2022 03:58:32 GMT
content-type: text/plain
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=oqZBnqCoBldB9xe1Zzr1K5qaYLEcrw9RaPnM%2FKoBBvhZ7G4U9IV2hZWLrWa9XW%2B4jdtkhYvFUa6H7eGja58kC2KCpcsygtupzDGkaFTtaTvze60nT39qugzQN7Br4Ymvz1RXFnSJbEXTS%2BDbMsM0BwUV"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
vary: Accept-Encoding
cf-ray: 755b7aabad2d8405-YVR
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
server: cloudflare
Connection: keep-alive
Keep-Alive: timeout=5

➤ curl --head "http://localhost:8787?length=48&no-content-type"
HTTP/1.1 200 OK
date: Thu, 06 Oct 2022 03:58:46 GMT
content-length: 48
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=ittpMWLmA%2BC0nlBTW%2BZmpTnh9VFjlwDilzBL4LOuoFQZ3x6dblcHpjMya3bm2v1LSOGxnzxZbAxQC2JyHF1flEk4C150W4DDXcP8pEBNHeO7cQMvFjreBzrzwTg0cSJYuqlLBHNlN71k6eh8HKwLi021"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
vary: Accept-Encoding
cf-ray: 755b7b04c93e8405-YVR
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
server: cloudflare
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by penalosa** [comment] 2022-10-07 09:41
I initially couldn't reproduce it, but I think I can now trigger it intermittently. We'll follow up internally to see what might be causing this (and thanks for the detailed reproduction steps), but in the meantime, would you be able to provide any more details on your original use case? Perhaps there's a workaround that we could help with?

**Comment by alukach** [comment] 2022-10-09 14:39
> would you be able to provide any more details on your original use case?

My use-case is that I am developing an API that is required to send the `content-length` header in response to HEAD requests.  Downstream clients throw errors if this header is not present in the responses.

> Perhaps there's a workaround that we could help with?

As mentioned in the original comment, this can be avoided by running Wrangler dev with the `--local` flag, so I'm not currently blocked.

I note that others have been able to reproduce this issue:

* https://github.com/honojs/hono/issues/577#issuecomment-1264553136
* https://community.cloudflare.com/t/content-length-header-missing-when-content-type-present/423568/2

---

I don't think this is an emergency or top priority, but would argue that this bug:

1. demonstrates a small level of instability on the part of wrangler's dev server, which adds to a developer's cognitive load when developing applications with Wrangler2
2. can be a bit of a time suck for future developers who are developing applications and burn a number of hours trying to figure out why their API clients are not properly interacting with their local Wrangler-dev-hosted API.

As an aside, I will mention that my experience with Wrangler2 has been great and I'm having a fun time onboarding to Cloudflare Workers.

**Comment by Bee7736** [comment] 2023-01-12 17:07
> ### คุณใช้เวอร์ชัน`Wrangler`อะไร
> 2.0.24
> 
> ### คุณใช้ระบบปฏิบัติการอะไร
> แม็ค
> 
> ### อธิบายข้อบกพร่อง
> เมื่อรัน`wrangler dev`ส่วน`Content-Length`หัวจะหายไปจากการตอบสนองหากมี`Content-Type`ส่วนหัวอยู่และมีค่า`Content-Length`มากกว่า`"47"`
> 
> #### สร้างจุดบกพร่องซ้ำ
> รายการขั้นตอนในการทำให้เกิดจุดบกพร่องซ้ำ
> 
> 1. สร้าง`src/index.ts`:
>    ```ts
>    // src/index.ts
>    export default {
>      async fetch(request: Request): Promise<Response> {
>        const query = new URL(request.url).searchParams;
>        const contentLength = query.get("length") || "0";
>        const useContentType = !query.has("no-content-type");
>    
>        return new Response(null, {
>          headers: {
>            "content-length": contentLength,
>            "content-type": useContentType ? "text/plain" : "",
>          },
>        });
>      },
>    };
>    ```
> 2. วิ่ง:
>    ```shell
>    wrangler dev src/index.ts
>    ```
> 3. ส่วนหัวทดสอบ:
>    ```shell
>    curl --head "http://localhost:8787?length=47" # Should see content-length & content-type header
>    curl --head "http://localhost:8787?length=48" # Will see only see content-type header
>    curl --head "http://localhost:8787?length=48&no-content-type" # Will only see content-length
>    ```
> 
> ตัวอย่างคำตอบ
> #### ทำงานรอบ ๆ
> ตามที่ค้นพบใน[ฟอรัมชุมชน Cloudflare](https://community.cloudflare.com/t/content-length-header-missing-when-content-type-present/423568/)สามารถหลีกเลี่ยงพฤติกรรมนี้ได้โดยการรัน`wrangler dev`ด้วย`--local`แฟล็ก ( `wrangler dev --local`)

**Comment by Sherlouk** [comment] 2023-01-16 00:35
I want to add to this thread that I am also seeing `Content-Length` is missing if `Content-Encoding` is present.

Unlike the above bug though, using `--local` doesn't seem to get around this issue. It seems impossible to have `Content-Encoding` and `Content-Length` at the same time.

**Comment by KianNH** [comment] 2023-01-23 11:51
In regards to the original issue, this appears to be explained by https://support.cloudflare.com/hc/en-us/articles/200168386-Why-is-my-dynamic-content-being-sent-with-chunked-encoding-

The response is being chunked when you're hitting 48 bytes, and hence there is no `content-length`.

```sh
################################################%
➜  ~ curl "http://localhost:8787?length=47" -vvv
*   Trying 127.0.0.1:8787...
* Connected to localhost (127.0.0.1) port 8787 (#0)
> GET /?length=47 HTTP/1.1
> Host: localhost:8787
> User-Agent: curl/7.86.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: text/plain
< content-length: 47
<
* Connection #0 to host localhost left intact
###############################################

➜  ~ curl "http://localhost:8787?length=48" -vvv
*   Trying 127.0.0.1:8787...
* Connected to localhost (127.0.0.1) port 8787 (#0)
> GET /?length=48 HTTP/1.1
> Host: localhost:8787
> User-Agent: curl/7.86.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: text/plain
< Transfer-Encoding: chunked
<
* Connection #0 to host localhost left intact
################################################
```

**Comment by Sherlouk** [comment] 2023-02-01 01:26
> That's not really an issue with Wrangler - that's how transparent decompression works.

I think there was a misunderstanding, but I have reviewed both your comments and indeed the one about the 48 bytes cutover and can indeed confirm that's the behaviour I'm seeing so is still linked to this thread.

The workarounds in the link provided seem to be to change the file path to include a cachable extension (which doesn't work for route based workers) or to add a page rule (which I don't believe can be done? I've tried adding a custom domain to my worker and then applying the page rule to that, but to the same result).

I've also tried `cache-control: no-transform` which was suggested elsewhere on the forum to a similar problem.

So it would seem, even with a known Content-Length, "Transfer-Encoding: chunked" overrides it. The content length is still helpful in order to show users a progress bar and other functionality - so this is definitely desirable to have if folks know of other workarounds.

**Comment by admah** [comment] 2023-02-06 16:14
@Sherlouk this issue is not one that we're going to be able to solve in Wrangler since it is a matter of how Cloudflare itself is handling the request. I'm going to close this and encourage you to open up a discussion on https://community.cloudflare.com/ about this issue.

**Closed by admah** 2023-02-06 16:14 UTC
Labels: bug, awaiting dev response
