### ISSUE TITLE
Port 9229 in use

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/wrangler2#21] opened 2021-11-16 15:56 UTC
When trying to run `wrangler dev` I get
> Error: listen EADDRINUSE: address already in use :::9229

It seems this is used for dev tools as per:
https://github.com/cloudflare/wrangler2/blob/6937fe9bd07b23c3f8c481e0a11128615356ef64/packages/wrangler/src/dev.tsx#L644

It appears this is not properly closing or it's being hung somewhere. I cannot see the port in something like `netstat` or `lsof`. Trying to kill all node processes yielded no success either (no process found).

@AlbertSPedersen is also able to reproduce this (both of us using Linux - _he runs Arch by the way_)

**Comment by threepointone** [comment] 2021-11-16 16:00
Thanks for the catch, I heard a couple of other people also bump into this. For one, maybe we should use a different port altogether, since 9229 is used by other tools as well, and we own the whole thing. But we shouldn't leave any hanging processes. I'll investigate, thank you for the report!

**Comment by ObsidianMinor** [comment] 2021-11-16 16:26
We should really make it customizable just in case.

**Comment by WalshyDev** [comment] 2021-11-24 01:14
I took a deeper dive into this issue, for me at least the issue is when I use `--local`. It works perfectly fine in remote mode.

Looking at why it works for one and not the other, it seems the delay introduced in remote (due to `useProxy`) is what is causing that one to work. Watching netstat, I can't determine why it can't work right away.

If you cause the error a few times though then the port doesn't close properly and gets stuck
```
tcp        0      0 127.0.0.1:9229          0.0.0.0:*               LISTEN
36102/node
```

`ps -p 36102  -o comm,args=ARGS`
```
COMMAND         ARGS
node            node --experimental-vm-modules --inspect /home/walshy/Workspace/NodeJS/wrangler2/packages/wrangler/node_modules/miniflare/dist/src/cli.js ../../../../../tmp/tmp-36084-YAz6uJrOdgRe/index.js --watch --wrangler-config /home/walshy/Workspace/NodeJS/wrangler2/packages/wrangler/miniflare-config-stubs/wrangler.empty.toml --env /home/walshy/Workspace/NodeJS/wrangler2/packages/wrangler/miniflare-config-stubs/.env.empty --package /home/walshy/Workspace/NodeJS/wrangler2/packages/wrangler/miniflare-config-stubs/package.empty.json --port 8787 --kv-persist --cache-persist --modules false
```

From what I can tell, quite a few node monitoring things (like node-inspector) use port 9229. Not sure if something is trying to open or what but yeah.
If I change the port to 9230 then it works flawlessly right away. So I agree with you both on changing the port and having it be customizable. I can do a PR for that if you'd like.

**Comment by jgentes** [comment] 2021-12-06 20:25
I run into this every time I try to use local mode on WSL2.

I think the issue is when we launch `wrangler dev` [it spawns node with the `--inspect` flag](https://github.com/cloudflare/wrangler2/blob/bf67bf2b365722351bad8dedaf0633c42ff22f34/packages/wrangler/src/dev.tsx#L241).

This will use port 9229 (you can see it with `lsof -i:9229` after launching wrangler dev). So when local mode tries to use the same port, it is already in use.

**Comment by hstatic** [comment] 2021-12-20 16:53
Having the same issue when running `wrangler dev` on a fresh Docker image (node:16-alpine).

**Comment by motiejunas** [comment] 2021-12-20 16:54
Having the same issue when running wrangler dev on a fresh Docker image (node:16-alpine).

**Comment by JacobMGEvans** [comment] 2021-12-28 18:19
@threepointone is this resolved with?
```ts
       .option("port", {
          describe: "Port to listen on, defaults to 8787",
          type: "number",
          default: 8787,
        })
```

Likely can be closed.

**Comment by threepointone** [comment] 2021-12-28 18:20
No, we still need to check why 9229 gets blocked. And potentially allow inspector port to start on a new port.

**Comment by geryit** [comment] 2022-01-28 17:23
What is the status of this?

**Comment by petebacondarwin** [comment] 2022-01-31 20:33
It is still something we need to work on. Hopefully as part of 2.0.0.

**Closed** 2022-03-02 14:02 UTC
Labels: bug
