### ISSUE TITLE
🐛 BUG: error incomplete input when executing SQL which can be exceuted by sqlite3 command

### ISSUE THREAD

**Issue by jo32** [cloudflare/wrangler2#2411] opened 2022-12-14 09:26 UTC
### What version of `Wrangler` are you using?

2.6.2

### What operating system are you using?

Mac

### Describe the Bug

not able to deploy SQL below:
```
DROP TABLE IF EXISTS "Program";
CREATE TABLE IF NOT EXISTS "Program" (
	"programId"	INTEGER,
	"programUuid"	TEXT NOT NULL,
	"programTitle"	TEXT NOT NULL,
	"programDescription"	TEXT NOT NULL,
	"programIcon"	TEXT NOT NULL,
	"programDownloadKey"	TEXT NOT NULL,
	"programAuthor"	TEXT NOT NULL,
	"createAt"	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updateAt"	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("programId" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "ProgramRecommendation";
CREATE TABLE IF NOT EXISTS "ProgramRecommendation" (
	"recommendationId"	INTEGER,
	"recommendationUuid"	TEXT NOT NULL,
	"programId"	INTEGER NOT NULL,
	"coverImageKey"	TEXT NOT NULL,
	"createAt"	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updateAt"	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY("programId") REFERENCES "Program"("programId"),
	PRIMARY KEY("recommendationId" AUTOINCREMENT)
);
DROP INDEX IF EXISTS "Program_programUuid";
CREATE INDEX IF NOT EXISTS "Program_programUuid" ON "Program" (
	"programUuid"
);
DROP INDEX IF EXISTS "Program_programTitle_programDescription";
CREATE INDEX IF NOT EXISTS "Program_programTitle_programDescription" ON "Program" (
	"programTitle",
	"programDownloadKey"
);
DROP INDEX IF EXISTS "Program_programAuthor";
CREATE INDEX IF NOT EXISTS "Program_programAuthor" ON "Program" (
	"programAuthor"
);
DROP INDEX IF EXISTS "ProgramRecommendation_recommendationUuid";
CREATE INDEX IF NOT EXISTS "ProgramRecommendation_recommendationUuid" ON "ProgramRecommendation" (
	"recommendationUuid"
);

DROP TRIGGER IF EXISTS "Program_update_updateAt";
CREATE TRIGGER Program_update_updateAt
AFTER UPDATE ON Program
FOR EACH ROW
WHEN NEW.updateAt <= OLD.updateAt
BEGIN
    UPDATE Program
    SET updateAt = CURRENT_TIMESTAMP
    WHERE programId = OLD.programId;
END;
DROP TRIGGER IF EXISTS "ProgramRecommendation_update_updateAt";
CREATE TRIGGER ProgramRecommendation_update_updateAt
AFTER UPDATE ON ProgramRecommendation
FOR EACH ROW
WHEN NEW.updateAt <= OLD.updateAt
BEGIN
    UPDATE ProgramRecommendation
    SET updateAt = CURRENT_TIMESTAMP
    WHERE recommendationId = OLD.recommendationId;
END;
```

it shows:

```
ERROR 9009: SQL prepare error: incomplete input [code: 7500]
```

both on local and deploying

however, I can execute it successfully by sqlite3 command:

```
sqlite3 -init ./schema.sql test.db
```

where schema.sql contains the SQL pasted above.

**Comment by admah** [comment] 2022-12-21 16:48
@jo32 thanks for reporting this. We'll take a look.

cc: @rozenmd

**Comment by rozenmd** [comment] 2022-12-28 10:52
@jo32 could you please try again and confirm the issue is fixed?

**Comment by admah** [comment] 2023-01-23 16:24
@jo32 I'm going to close this assuming that the issue has been fixed per @rozenmd comment. If the issue persists please reopen the issue. Thanks!

**Closed by admah** 2023-01-23 16:24 UTC
Labels: bug, d1

**Comment by code-poel** [comment] 2023-05-08 16:17
Hello, I'm experiencing this issue as well.   Simple trigger in the schema file will result in `ERROR 9009: SQL prepare error: incomplete input [code: 7500]`.  Removal of the create trigger statement will result in the DB queries to execute just fine.  Wrangler 2.19.0.
