### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by vlpsebas** [cloudflare/wrangler2#2417] opened 2022-12-15 18:08 UTC
### What version of `Wrangler` are you using?

2.2.1

### What operating system are you using?

Linux

### Describe the Bug

Got this error when attempted "wrangler dev" command:

<In development, you should use a separate kv namespace than the one you'd use in production. Please create a new kv namespace with "wrangler kv:namespace create <name> --preview" and add its id as preview_id to the kv_namespace "weatherapi" in your wrangler.toml>

After updating and publishing the changes requested, received: 

<Processing wrangler.toml configuration:
    - "kv_namespaces[1]" bindings should have a string "id" field but got
  {"binding":"testweather","preview_id":"fe8a24542fba42d9a1f17421ec57ac00"}.>

**Comment by admah** [comment] 2022-12-21 16:46
@vlpsebas thanks for submitting this. The issue is that you need an `id` in order to create a KV Namespace via Wrangler. Please refer to our docs on creating those via Wrangler [here](https://developers.cloudflare.com/workers/wrangler/workers-kv/).

Closing this for now.

**Closed by admah** 2022-12-21 16:46 UTC
Labels: bug
