### ISSUE TITLE
feature request: inject special env vars/runtime vars to detect `--local` mode

### ISSUE THREAD

**Issue by maraisr** [cloudflare/wrangler2#899] opened 2022-05-04 21:44 UTC
With miniflare one could inject an environment variable in build scripts to delineate slightly differently between a _real_ worker and one that runs locally.

see

https://github.com/cloudflare/miniflare/blob/5d9032470247173c54f4fecfc4f7750f10beaee8/packages/core/src/plugins/build.ts#L73

This is helpful to get around the lack of support of secrets so could be used like;

```js
// file: my-app.js

const get_jwt_factory = (secret) =>
   HS256({
     key: secret,
     expires: 86400, // 24 hours
   });

export const jwt = (env) => get_jwt_factory(__DEV__ ? 'test-key' : env.JWT_SECRET);

// file: worktop.config.js

import { define } from 'worktop.build';

export default define({
	modify(config) {
		config.define = {
			__DEV__: JSON.stringify(process.env.MINIFLARE === '1'),
		};
	},
});
```

would be nice to bring this environment variable back.

**Comment by threepointone** [comment] 2022-05-04 21:58
We landed initial support for dotenv style injection in https://github.com/cloudflare/wrangler2/pull/879 tldr make a file called .dev.vars in your project root

**Comment by maraisr** [comment] 2022-05-04 22:06
I recognise that https://github.com/cloudflare/wrangler2/pull/879 partly solves it. Would still be nice to `__DEV__`, like for example to not send tracing information to newrelic during dev time.

**Comment by petebacondarwin** [comment] 2022-05-05 06:58
One way to do this right now would be to have a the following in your `.dev.vars` file:

```
__DEV__ = true
```

Then in your code you can do:

```
export async function fetch(reques, env) {
  if (env.__DEV__) { ... }
}
```

Right?

**Comment by threepointone** [comment] 2022-05-05 07:08
I'm not clear on what the ask is here, and what we regressed . Could you clarify?

**Comment by maraisr** [comment] 2022-05-05 07:32
miniflare told build scripts it was miniflare building it
wrangler 2 doesnt do that.

re @petebacondarwin's point, that wont work as then runtime code is built and shipped. Whole point is to make it a built-time variable so treeshaking/DCE and happen more effectively. 

only workaround is;

```toml
// file: prod.wrangler.toml

[build]
command = "npm run build"

// file: dev.wrangler.toml

[build]
command = "DEV=1 npm run build"
```

and then have my build script react to that, and then some whaky `cp prod.wrangler.toml wrangler.toml` as a `predeploy` npm script.

**Comment by threepointone** [comment] 2022-05-05 10:28
I think a better solution is would be to use environments. In your `wrangler.toml`, you can set up

```toml
[vars]
secret = 'actual-key'

[build]
command = "npm run build"

[env.dev.vars]
secret = 'test-key'

[env.dev.build]
command = "DEV=1 npm run build"
```

So you can run `wrangler dev --env dev` and it'll load `test-key`. 

To be clear, this tackles multiple separate issues - 
- injecting variables into a build time process, which you can with regular system environment variables. We also landed `dotenv` support, so you can use `.env` files as well.  
- injecting runtime vars, which you can do with `wrangler.toml`/`--env`/`[vars]`
- additionally, if you want to inject variables _only_ during `wrangler dev` you can use `dev.vars`, which uses `dotenv` syntax. 

I don't think we have any plans right now to introduce any variables to detect whether we're running local vs remote modes, but I'll leave this issue open till we actually discuss and decide. This is also not a regression since we never supported it, and I've amended the title to reflect that.

**Closed** 2022-05-05 10:33 UTC
