### ISSUE TITLE
🐛 BUG: D1 erroring on big sqlite dump import

### ISSUE THREAD

**Issue by MinmoTech** [cloudflare/wrangler2#2414] opened 2022-12-14 18:27 UTC
### What version of `Wrangler` are you using?

2.4.2

### What operating system are you using?

Linux (archlinux)

### Describe the Bug

While trying to import a very big sqlite dump (121098 lines) I get the following error:
```
$ wrangler d1 execute audio --file ./out.sq
🚧 'wrangler d1 <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
🌀 Mapping SQL input into an array of statements
🌀 Parsing 121092 statements
🌀 We are sending 13 batch(es) to D1 (limited to 10000 statements per batch)
⚠️  Too much SQL to send at once, this execution will be sent as 13 batches.
ℹ️  Each batch is sent individually and may leave your DB in an unexpected state if a later batch fails.
⚠️  Make sure you have a recent backup. Ok to proceed? (y/n)
🌀 Let's go
🌀 Executing on table_name (fc09486d-3681-4906-a109-0b5e3d7737ab):
🚣 Executed 10000 commands in 596.1690040379763ms
...
🚣 Executed 10000 commands in 543.2455580718815ms
...
🚣 Executed 10000 commands in 655.4711569435894ms
...
✘ [ERROR] A request to the Cloudflare API (/accounts/285b637e867fade495c9dd74d250fa0b/d1/database/fc09486d-3681-4906-a109-0b5e3d7737ab/query)failed.

  Error 9000: exception caught in D1 core. Maximum number of keys modified in a transaction is 128.
  Error: Maximum number of keys modified in a transaction is 128.
      at Object.m [as putPage] (worker.js:2595:29)
      at put_page (worker.js:2438:15)
      at worker.js:2267:15
      at wasm://wasm/00f4590e:wasm-function[49]:0x863a
      at wasm://wasm/00f4590e:wasm-function[3209]:0x1d220e
      at wasm://wasm/00f4590e:wasm-function[3186]:0x1cd0d2
      at wasm://wasm/00f4590e:wasm-function[3189]:0x1cdb39
      at wasm://wasm/00f4590e:wasm-function[3242]:0x1d7673
      at wasm://wasm/00f4590e:wasm-function[3300]:0x1eadf0
      at wasm://wasm/00f4590e:wasm-function[3297]:0x1dd6c9 [code: 7500]
```

My sql file looks similar to the following:
```sql
CREATE TABLE table_name(
  entry1 TEXT NOT NULL,
  entry2 TEXT NOT NULL,
  entry3 INTEGER NOT NULL,
  entry4 TEXT,
  PRIMARY KEY (entry1, entry2)
);
INSERT INTO table_name VALUES('text','text',0,'');
```
With the `INSERT INTO` repeating until the end of the file

**Comment by nevikashah** [comment] 2023-01-09 15:21
Duplicate of https://github.com/cloudflare/wrangler2/issues/2399

**Comment by rozenmd** [comment] 2023-01-09 15:21
Closing as duplicate

**Closed by rozenmd** 2023-01-09 15:21 UTC
Labels: blocked, bug, internal, d1

**Comment by rozenmd** [comment] 2023-05-24 16:41
Hey @MinmoTech,
We recently released a new D1 backend which fixes this issue, you can read more about it here: https://blog.cloudflare.com/d1-turning-it-up-to-11/
