### ISSUE TITLE
 bug: invalid worker names shouldn't be allowed

### ISSUE THREAD

**Issue by Leptopoda** [cloudflare/wrangler2#775] opened 2022-04-09 16:16 UTC
Wrangler authentication seems broken.
As seen below I'm on .25

```
 ⛅️ wrangler 0.0.25 
--------------------

✘ [ERROR] Received a bad response from the API

  PUT method not allowed for the oauth_token authentication scheme [code: 10000]
```

**Comment by threepointone** [comment] 2022-04-09 16:36
Could you share some more information? What command do you run, what does your wrangler.toml look like, etc. Also, could you try running `wrangler logout`/`wrangler login` again and trying?

**Comment by Leptopoda** [comment] 2022-04-09 21:35
Hi there, 
Sorry for my bad bug report (I was on the go).

Off cause I've tried logout/login even deleting `~/.wrangler/` as I've just recently switched from wranglerV1 and there was still some stuff from v1 in there. 
> What command do you run

I've just created a new project with `wrangler init .` and wanted to publish it with `npm run publish` (trying `wrangler publish` results in the same behavior).
The same behavior can also be seen when using `wrangler dev`:
```
 ⛅️ wrangler 0.0.25 
--------------------
⬣ Listening at http://localhost:8787
remote worker: ParseError: Received a bad response from the API
    at throwFetchError (/usr/lib/node_modules/wrangler/wrangler-dist/cli.js:137650:17)
    at fetchResult (/usr/lib/node_modules/wrangler/wrangler-dist/cli.js:137623:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createPreviewToken (/usr/lib/node_modules/wrangler/wrangler-dist/cli.js:139904:29)
    at async createWorkerPreview (/usr/lib/node_modules/wrangler/wrangler-dist/cli.js:139919:17)
    at async start (/usr/lib/node_modules/wrangler/wrangler-dist/cli.js:140357:16) {
  text: 'Received a bad response from the API',
  notes: [
    {
      text: 'POST method not allowed for the oauth_token authentication scheme [code: 10000]'
    }
  ],
  location: undefined,
  kind: 'error',
  code: 10000
}

```
As a result of the fresh project the wrangler.toml is still the default one:

```
name = "."
main = "src/index.ts"
compatibility_date = "2022-04-09"

```

My `~/.wrangler/config/default.toml` also seems to be intact

```
oauth_token ="*** "
expiration_time = "2022-04-09T22:06:46.438Z"
refresh_token = "*** "
```

**Comment by threepointone** [comment] 2022-04-10 12:22
That's not great, sorry about that. I'll have a look soon. I'm afk right now, but could you change the `name` in `wrangler.toml` to something like "test" and try again? "." isn't a valid worker name, and may be confusing our api. We should, regardless, fix the name generation logic ourselves there, but I wonder if that's what's messing it up for you right now.

**Comment by threepointone** [comment] 2022-04-10 13:04
Yup, I can confirm that's what the problem was, can reproduce it myself. We'll add validation for worker names soon. Thanks for reporting this!

**Comment by Leptopoda** [comment] 2022-04-10 17:18
That's indeed it.

I thought wrangler init takes the dir as a parameter so I did `wrangler init .` but that was definitely wrong.
Thanks :upside_down_face:

**Comment by threepointone** [comment] 2022-04-10 17:30
It probably should take the arg to be a destination, not just a plain name.

**Comment by petebacondarwin** [comment] 2022-04-11 11:07
I think we take the basename of the current directory as the worker name if none is provided right now. So perhaps we should just grab the <name> arg and resolve it against the current working directory?

**Comment by threepointone** [comment] 2022-04-11 11:35
Yup agreed, that's what I'm thinking too

**Comment by threepointone** [comment] 2022-04-13 12:56
Marking this for 2.0, it's likely it'll confuse a bunch of people if we don't do this.

**Comment by JacobMGEvans** [comment] 2022-04-15 23:36
I can get the RegEx used by the Dashboard and Frontend and apply it to the Config validation for name.

**Comment by threepointone** [comment] 2022-05-02 06:50
The PR didn't solve the original problem, of using the directory name as the worker name. Reopening.

**Comment by threepointone** [comment] 2022-05-03 08:10
fixed by https://github.com/cloudflare/wrangler2/pull/877

**Closed by threepointone** 2022-05-03 08:10 UTC
Labels: bug
