### ISSUE TITLE
Running `wrangler dev` from an E2E test throws Ink errors

### ISSUE THREAD

**Issue by geelen** [cloudflare/wrangler2#322] opened 2022-01-27 19:09 UTC
Trying this inside a Jest test, running through [shellac](https://github.com/geelen/shellac)

```
> wrangler dev --local src/worker.ts "--port" "1983"

Something went wrong:
Error: Raw mode is not supported on the current process.stdin, which Ink uses as
 input stream by default.
Read about how to prevent this error on
https://github.com/vadimdemedes/ink/#israwmodesupported
    at App.handleSetRawMode (/Users/glen/src/projects/holodb/node_modules/.pnpm/
wrangler@0.0.12/node_modules/wrangler/wrangler-dist/cli.js:76028:21)
    at /Users/glen/src/projects/holodb/node_modules/.pnpm/wrangler@0.0.12/node_m
odules/wrangler/wrangler-dist/cli.js:76665:9
    at invokePassiveEffectCreate (/Users/glen/src/projects/holodb/node_modules/.
pnpm/wrangler@0.0.12/node_modules/wrangler/wrangler-dist/cli.js:24776:28)
    at Object.invokeGuardedCallbackProd (/Users/glen/src/projects/holodb/node_mo
dules/.pnpm/wrangler@0.0.12/node_modules/wrangler/wrangler-dist/cli.js:22171:19)
    at invokeGuardedCallback (/Users/glen/src/projects/holodb/node_modules/.pnpm
/wrangler@0.0.12/node_modules/wrangler/wrangler-dist/cli.js:22258:39)
    at flushPassiveEffectsImpl (/Users/glen/src/projects/holodb/node_modules/.pn
pm/wrangler@0.0.12/node_modules/wrangler/wrangler-dist/cli.js:24838:17)
    at unstable_runWithPriority (/Users/glen/src/projects/holodb/node_modules/.p
npm/wrangler@0.0.12/node_modules/wrangler/wrangler-dist/cli.js:8735:20)
    at runWithPriority (/Users/glen/src/projects/holodb/node_modules/.pnpm/wrang
ler@0.0.12/node_modules/wrangler/wrangler-dist/cli.js:15515:18)
    at flushPassiveEffects (/Users/glen/src/projects/holodb/node_modules/.pnpm/w
rangler@0.0.12/node_modules/wrangler/wrangler-dist/cli.js:24742:22)
    at /Users/glen/src/projects/holodb/node_modules/.pnpm/wrangler@0.0.12/node_m
odules/wrangler/wrangler-dist/cli.js:24661:19
```

**Comment by threepointone** [comment] 2022-01-27 19:33
using wrangler inside tests is on our roadmap, but we haven't figured out the details yet. If you have a quick fix for this specific issue, happy to accept a PR!

**Comment by petebacondarwin** [comment] 2022-01-27 20:17
The problem is that any Ink component that use the `useInput()`, or similar hooks, expects to run in an interactive console.
It is not just a problem when writing tests: https://github.com/cloudflare/wrangler2/issues/170

**Closed** 2022-03-28 11:08 UTC
Labels: bug
