### ISSUE TITLE
🐛 BUG: RegEx output not as expected

### ISSUE THREAD

**Issue by VR-Architect** [cloudflare/wrangler2#2424] opened 2022-12-16 17:54 UTC
### What version of `Wrangler` are you using?

2.6.1

### What operating system are you using?

Windows 10

### Describe the Bug

Running this RegEx results in a false when it should be a true. It is a test for a password meeting minimum requirements per this article https://www.computerworld.com/article/2833081/how-to-validate-password-strength-using-a-regular-expression.html 

I tested the sample password (a1!A1qaz) on a couple of online regex testers and the expression results as a match there.

- https://regexr.com/
- https://regex101.com/
- https://www.regextester.com/

```
var regexp2 = new RegExp('(?=^.{8,}$)(?=.*\d)(?=.*[!@#$%^&*]+)(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$')
var validPasword = regexp2.test('a1!A1qaz'); 
```

**Comment by VR-Architect** [comment] 2022-12-16 18:06
I believe the above is still a bug; however, I found this work around in case anyone else is interested. It is from this article:
https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s19.html

```
function validatePasswordComplexity(password) {
    var minMaxLength = /^[\s\S]{8,32}$/,
        upper = /[A-Z]/,
        lower = /[a-z]/,
        number = /[0-9]/,
        special = /[ !"#$%&'()*+,\-./:;<=>?@[\\\]^_`{|}~]/;

    if (minMaxLength.test(password) &&
        upper.test(password) &&
        lower.test(password) &&
        number.test(password) &&
        special.test(password)
    ) {
        return true;
    }

    return false;
}
```

**Comment by admah** [comment] 2022-12-21 16:34
@VR-Architect we are going to track this internally. We've passed it to the Runtime team for them to evaluate.

**Comment by jasnell** [comment] 2023-01-20 19:43
In looking at this, both Node.js and Chrome also agree that the valid result of that test case is `false`. I'm not seeing any bug here.

**Comment by lrapoport-cf** [comment] 2023-01-23 16:47
closing this as is it not a bug. the internally tracked ticket has also been closed.

**Closed by lrapoport-cf** 2023-01-23 16:47 UTC
Labels: blocked, bug, internal
