### ISSUE TITLE
Option to cleanup after "EADDRINUSE: address already in use"

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#376] opened 2022-02-02 23:14 UTC
If wrangler crashes during a dev session, for whatever reason, you can't start a new session because the port was left open. Instead of Googling different ways to close the port (not fun), wrangler should prompt the user and ask if they wish to close the port. Here is a proposed flow:

If wrangler encounters "EADDRINUSE" while opening a port, it prompts user if they want to continue by closing the port. If yes, close the port and retry. If no, exit and suggest they use `--port` to change the port.

**Comment by petebacondarwin** [comment] 2022-02-03 07:13
Is this a duplicate of https://github.com/cloudflare/wrangler2/issues/21?

**Comment by threepointone** [comment] 2022-02-03 09:52
related to https://github.com/cloudflare/wrangler2/issues/340?

**Comment by threepointone** [comment] 2022-03-08 18:59
https://github.com/cloudflare/wrangler2/pull/519 should have fixed this in that you can start up a new instance without clashing, but we should investigate the port being occupied after closing

**Comment by threepointone** [comment] 2022-03-27 20:16
We cleanup the process properly now, so there shouldn't be hanging ports. I'm going to close this, but feel free to reopen if it happens again.

**Closed by threepointone** 2022-03-27 20:16 UTC
Labels: polish
