### ISSUE TITLE
🐛 BUG: kv-binding goes wrong?

### ISSUE THREAD

**Issue by s0urcelab** [cloudflare/wrangler2#986] opened 2022-05-13 05:57 UTC
### What version of `Wrangler` are you using?

2.0.3

### What operating system are you using?

Windows 10

### Describe the Bug

kv-binding goes wrong?

i've create a kv and bind it in wrangler.toml:
```
kv_namespaces = [
  { binding = "COMMENTS", id = <my key> }
]
````
(i can confirm it on Cloudflare dashboard.)

but when i call `COMMENTS`, throw a error `ReferenceError: COMMENTS is not defined`:

index.js:

```
export default {
  async fetch(request) {

    let value = await COMMENTS.get('aaa');

    // Return the value, as is, for the Response
    return new Response(value)
  },
};
```

wrangler cli error:
```
下午1:43:19 GET / 500
✘ [ERROR] Uncaught (in promise) ReferenceError: COMMENTS is not defined

      at Object.fetch (index.js:4:17)


✘ [ERROR] Uncaught (in response) ReferenceError: COMMENTS is not defined


✘ [ERROR] Uncaught (in promise) ReferenceError: COMMENTS is not defined

      at Object.fetch (index.js:4:17)


✘ [ERROR] Uncaught (in response) ReferenceError: COMMENTS is not defined
```

but if i use the `env.COMMENTS` everything works fine:
```
export default {
  async fetch(request, env) {

    let value = await env.COMMENTS.get('aaa');

    // Return the value, as is, for the Response
    return new Response(value)
  },
};

```

**Comment by threepointone** [comment] 2022-05-13 06:28
This is as designed. When you write a worker as a service-worker format (i.e. with `addEventListener('fetch', () => `), then bindings are available as globals in the Worker. When using the modules format worker (i.e with `export default { fetch(request, env) {...`) then bindings are available on `env`. Sorry for the confusion! We should have easily referrable docs on this, and I'll follow up on this internally. 

Closing this issue since it works as expected.

**Closed by threepointone** 2022-05-13 06:28 UTC

**Comment by koeninger** [comment] 2022-05-13 17:46
https://developers.cloudflare.com/workers/runtime-apis/kv/#referencing-kv-from-durable-objects-and-workers-using-modules-syntax
