### ISSUE TITLE
🐛 BUG: Broken file paths using worker sites

### ISSUE THREAD

**Issue by OttoHatt** [cloudflare/wrangler2#1135] opened 2022-05-28 09:29 UTC
### What version of `Wrangler` are you using?

2.0.7

### What operating system are you using?

Windows

### Describe the Bug

I'm not entirely sure what's happening, but it looks like file paths are relative to the `wrangler.toml` file rather than `site.bucket`, meaning files can't be resolved in worker sites. This happens for me with any workers site (on any workers.dev upload, public and development).

**To reproduce:**
[Using this official example...](https://github.com/cloudflare/templates/tree/main/worker-sites-react)
```
npm init cloudflare my-project worker-sites-react
npm i wrangler -D
npx wrangler dev
(open web browser; all JS & CSS 404s)
```
![image](https://user-images.githubusercontent.com/68089630/170819460-0081b7ac-cc2e-476d-9762-cc002f5712c0.png)

**Other details:**
* Does not happen in local emulation (i.e. `npx wrangler dev --local`); uploading to workers.dev seems to be the broken part.
* This behaviour isn't present in wrangler 1; the example works correctly when uploaded to workers.dev (with addition of `entry-point = "workers-site"` to the config file).

thank you!

**Comment by petebacondarwin** [comment] 2022-05-30 16:29
I can reproduce this on Windows.

**Comment by petebacondarwin** [comment] 2022-05-30 16:32
And I believe the problem is related to https://github.com/cloudflare/wrangler2/pull/1137 although that doesn't appear to fix this problem...

**Comment by petebacondarwin** [comment] 2022-05-30 16:36
Actually it is fixed by that PR. You can test this by installing `npm i -D wrangler@beta`. This functionality will be in the next patch release.

**Closed by petebacondarwin** 2022-05-30 16:36 UTC
Labels: bug

**Comment by sixlettervariables** [comment] 2022-06-03 11:54
This was exceptionally hard to find as the cause until I did:
```
console.log(__STATIC_CONTENT_MANIFEST)
```
And saw:
```
{
...
 "static\\css\\main.b895efcf.chunk.css":"build/static/css/main.b895efcf.chunk.b20e7d9a46.css",
...
}
```
