### ISSUE TITLE
🐛 BUG: `pages dev` HTTP 406 on `env.ASSETS.fetch()`

### ISSUE THREAD

**Issue by Mexican-Man** [cloudflare/wrangler2#370] opened 2022-02-01 23:56 UTC
### What version of `Wrangler` are you using?

0.0.15

### What operating system are you using?

Windows

### Describe the Bug

Try this:
```ts
export const onRequestGet: PagesFunction<{}> = async ({ request, env, next, data, params }) => {
    const cloned = request.clone();
    const dest = `https://some-page.dev/`;
    return env.ASSETS.fetch(new Request(dest, { headers: cloned.headers }));
};
```
Run `wrangler pages dev ./`

Works as expected on Wrangler, fetches the index page for `https://some-page.dev/`. On Pages, `env.ASSETS.fetch()` returns a `406` error with no body. I've confirmed that it is `env.ASSETS.fetch()` that's returning the error, and that the worker isn't just dying.

Here's an example response:
```json
        "response": {
          "status": 406,
          "statusText": "",
          "httpVersion": "h3",
          "headers": [
            {
              "name": "date",
              "value": "Tue, 01 Feb 2022 23:53:01 GMT"
            },
            {
              "name": "content-length",
              "value": "0"
            },
            {
              "name": "expect-ct",
              "value": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
            },
            {
              "name": "report-to",
              "value": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=SEj8%2BhNNl%2F31mCPN76ltZtRFew7hoKTHlFyXPakdNoR2dpBUfCsl%2FaDStznbbAG6ZtmGQaCrIGJpV9fr3QFs%2BubBDV5Hi8fRKNLq3LB6sBCB3wUTt5Paa63t%2FN6Yz9djp6NE\"}],\"group\":\"cf-nel\",\"max_age\":604800}"
            },
            {
              "name": "nel",
              "value": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}"
            },
            {
              "name": "vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "cf-cache-status",
              "value": "DYNAMIC"
            },
            {
              "name": "server",
              "value": "cloudflare"
            },
            {
              "name": "cf-ray",
              "value": "6d6f18c83c5e840e-YVR"
            },
            {
              "name": "alt-svc",
              "value": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400"
            }
          ],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "text/plain"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 514,
          "_error": "net::ERR_HTTP_RESPONSE_CODE_FAILURE"
        },
```

**Comment by Cherry** [comment] 2022-04-16 23:15
I also ran into this issue today when attempting to migrate an older Workers Sites project.

My use-case here is an `index.html`, and `test.html`. I want to serve the `index.html` unless there's a query parameter in the URL (like q), and in which case, get the `test.html` and run an `HTMLRewriter` over it.

Reproduction repo: https://github.com/Cherry/universe-horse-test
URL: https://universe-horse-test.pages.dev/
406 (works fine in dev, other than a redirect issue if I use the full path with `.html`): https://universe-horse-test.pages.dev/?test=1

**Comment by falcon03** [comment] 2022-07-20 08:53
I run across the same issue and can confirm this nasty bug. I got referenced to this issue from a topic in the Cloudflare community forum:

https://community.cloudflare.com/t/response-406-unacceptable-on-env-assets-fetch-for-yaml-file/400603

My use-case is trying to load a YAML file from my cloudflare pages project within a functions middleware (that is part of the same project). The code worked locally (using wrangler pages dev), but not in production!

**Comment by Mexican-Man** [comment] 2022-07-21 06:17
@falcon03, a workaround for this problem could look like this:
```ts
export const onRequestGet: PagesFunction<{}> = async ({ request }) => {
    return fetch("./myfile.yaml", request.url)
};
```
This does a regular fetch request, which piggybacks off the incoming request's URL. Of course, this requires that your YAML file publicly accessible. This would results in fetching `http://localhost/myfile.yaml` locally, and `https://something.pages.dev/myfile.yaml` when hosted.

**Comment by Cherry** [comment] 2022-08-04 21:09
This impacted another user in the Discord today: https://canary.discord.com/channels/595317990191398933/910978223968518144/1004857593656786974

Can we get some eyeballs on this issue please? It's a massive prod vs development issue when doing anything slightly advanced within Functions.

**Comment by Cherry** [comment] 2022-09-18 20:48
This doesn't just impact `env.ASSETS.fetch`. The following also triggers a 406, with an accompanying `test.html` file:

```js
// functions/testing.js
export async function onRequestGet({request, next}){
    const url = new URL(request.url);
    url.pathname = '/test';
    return next(url.toString());
}
```

**Comment by Cherry** [comment] 2023-01-02 18:09
I'm no longer able to reproduce this - it seems to be resolved.

**Comment by JacobMGEvans** [comment] 2023-01-12 23:09
Closing for now.

**Closed by JacobMGEvans** 2023-01-12 23:09 UTC
Labels: pages, bug, pages:validated, pages-shared
