### ISSUE TITLE
stdin secrets

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler2#328] opened 2022-01-27 23:59 UTC
`cat secret.txt | npx wrangler secret put MY_SECRET_NAME` should store the piped value.

```
  ERROR  Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
        Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported

 - Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported
 - App.handleSetRawMode (node_modules/wrangler/wrangler-dist/cli.js:76028:21)
 -  (node_modules/wrangler/wrangler-dist/cli.js:76665:9)
 - invokePassiveEffectCreate (node_modules/wrangler/wrangler-dist/cli.js:24776:28)
 - Object.invokeGuardedCallbackProd (node_modules/wrangler/wrangler-dist/cli.js:22171:19)
 - invokeGuardedCallback (node_modules/wrangler/wrangler-dist/cli.js:22258:39)
 - flushPassiveEffectsImpl (node_modules/wrangler/wrangler-dist/cli.js:24838:17)
 - unstable_runWithPriority (node_modules/wrangler/wrangler-dist/cli.js:8735:20)
 - runWithPriority (node_modules/wrangler/wrangler-dist/cli.js:15515:18)
 - flushPassiveEffects (node_modules/wrangler/wrangler-dist/cli.js:24742:22)
 -  (node_modules/wrangler/wrangler-dist/cli.js:24661:19)
 ```

**Comment by GregBrimble** [comment] 2022-01-28 00:28
Same error when you run `wrangler dev` with `concurrently`. Haven't completely tested it, but I think this is a regression. I'm guessing any stdin will make it blow up.

**Comment by petebacondarwin** [comment] 2022-01-28 07:12
Duplicate of #327 170

**Closed by petebacondarwin** 2022-01-28 07:12 UTC
Labels: bug
