### ISSUE TITLE
🐛 BUG: Inconsistency in content-types

### ISSUE THREAD

**Issue by kotx** [cloudflare/wrangler2#1129] opened 2022-05-27 17:09 UTC
### What version of `Wrangler` are you using?

2.0.6

### What operating system are you using?

MacOS Monterey 12.4 on M1

### Describe the Bug

Make a file called `xxx.txt` and try to access it locally after running `wrangler pages dev .`
Access `/xxx.txt` locally and see how content is displayed (and `content-type` is omitted)
Publish the pages with `wrangler pages publish .`
Access `/xxx.txt` from the pages.dev deployment and see how `content-type` is `application/octet-stream`.

**Comment by GregBrimble** [comment] 2022-05-27 21:58
Dupe of #593 . Thanks for the report!

**Closed by GregBrimble** 2022-05-27 21:58 UTC
Labels: pages, bug
