### ISSUE TITLE
🐛 BUG: wrangler pages publish incorrect handles directory names starting with underscore 

### ISSUE THREAD

**Issue by miohtama** [cloudflare/wrangler2#1296] opened 2022-06-18 15:01 UTC
### What version of `Wrangler` are you using?

2.0.14

### What operating system are you using?

Mac and Linux

#### Describe the bug

Wrangler fails correctly to upload folders starting with letter _ e.g. `_static` for Sphinx documentation tool.

These folders include common Sphinx folders like:

- `_static`
- `_images`
- `_source`

#### Reproduce the bug

[The Github workflow that triggers the bug](https://github.com/tradingstrategy-ai/trading-strategy/blob/76404d7be8ca147dc86505a1e958cc1e8eec7ccb/.github/workflows/cloudflare-pages.yml).

#### Expected behavior

With command ` (cd docs/build/html && npx wrangler pages publish . --project-name=trading-strategy-docs --branch test)` files are uploaded to Cloudflare Pages as they are on the filesystem directory structure.

```
.
./index.html
./searchindex.js
./_static
./_static/logo-square.png
./_static/favicon_32.png
```

The actual uploaded directory structure, as taken from from Cloudflare Pages dashboard:

```
index.html
favicon.svg
favicon_32.png
favicon_96.png
logo-square.png
````

As you can see, `wrangler`, without asking or reporting the matter, somehow managed to flatten `_static` folder away, making all Sphinx-generated CSS, JS and image resource links invalid.

#### Environment and versions

Fill out the following information about your environment.

```
 wrangler --version
2.0.14
```

**Comment by petebacondarwin** [comment] 2022-06-18 15:06
I believe that this is how "Cloudflare Pages" works. These particular underscore prefixed files have special meaning in Pages projects. I am not sure whether there is a way to configure them.

**Comment by miohtama** [comment] 2022-06-18 15:15
If it is a limitation of Cloudflare Pages and it cannot handle such directories, then I feel more correct behaviour would abort the upload with an error, instead of renaming directories.

**Comment by GregBrimble** [comment] 2022-06-19 23:09
Dupe of #938.

Pages does have some magic underscore-prefixed files, but we do support other files/folders with underscores in their names. It's just `_headers`, `_redirects` and `_worker.js` that are currently reserved names.

**Closed by GregBrimble** 2022-06-19 23:09 UTC
Labels: pages, bug
