### ISSUE TITLE
Local dev server uses the production CF worker instance

### ISSUE THREAD

**Issue by kevbook** [cloudflare/wrangler2#191] opened 2022-01-04 19:18 UTC
When using `wrangler dev` without the `--local` flag is not added, the dev system proxies to the production CF worker instance, and thus using default CF worker env vars. Is this the desired design?

**Comment by threepointone** [comment] 2022-01-05 11:25
Could you explain your question some more? It doesn't proxy to the production instance per se, and only uses the vars defined in `wrangler.toml`. Are you seeing any differently?

**Comment by kevbook** [comment] 2022-01-06 03:58
So I see what is happening. In the CF workers web UI, you'll have a default environment. Usually, that's `production` since Services was introduced (https://blog.cloudflare.com/introducing-worker-services). So when you do `wrangler dev`, it proxies your local environment to the default CF worker environment and hence you have access to the production environment variables on the `async fetch (request, env, context)` method.

![image](https://user-images.githubusercontent.com/926720/148325854-e3888d1e-6126-4ea2-ba28-111be7d8149e.png)
.

**Comment by threepointone** [comment] 2022-01-06 16:15
That shouldn't be the case, we shouldn't be leaking vars set in the dashboard during `dev`. I'll investigate this, I may be missing some context.

**Comment by threepointone** [comment] 2022-05-17 08:01
I verified that this is actually by design. We use vars and secrets as defined on the edge during dev, verlaid by the vars defined in development. This is particularly useful for secrets, since we never want to checkin secrets in wrangler.toml. We're working on refining permissions and scopes around environments, and will communicate more details for that as we have answers. Closing this issue.

**Closed by threepointone** 2022-05-17 08:01 UTC
Labels: needs clarification, bug
