### ISSUE TITLE
🐛 BUG: `wrangler logout` attempts to log me back in immediately

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/wrangler2#2141] opened 2022-11-08 03:00 UTC
### What version of `Wrangler` are you using?

2.1.15

### What operating system are you using?

Mac

### Describe the Bug

```sh
npx wrangler logout
 ⛅️ wrangler 2.1.15
--------------------
Successfully logged out.
Attempting to login via OAuth...
```

**Comment by JacobMGEvans** [comment] 2022-11-10 16:46
Oh that is weird... Wonder what is causing that.

**Comment by threepointone** [comment] 2022-11-15 11:42
I can confirm this is happening too. Seems bad.

**Comment by threepointone** [comment] 2022-11-16 18:07
Hrmm, I can't reproduce this with 2.3.1 either. Odd. I'll keep an eye on it.

**Comment by jspspike** [comment] 2023-01-23 16:49
Closing for now, likely fixed with ink changes. Feel free to reopen if the error occurs again

**Closed by jspspike** 2023-01-23 16:49 UTC
Labels: bug
