### ISSUE TITLE
Github Codespaces: spawn xdg-open ENOENT on wrangler dev

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/wrangler2#23] opened 2021-11-16 18:20 UTC
Really excited about this! I gave this a spin in Github Codespaces and ran into the following:

```
@irvinebroque ➜ /workspaces/project (main ✗) $ wrangler dev src/worker/index.ts
/usr/local/share/nvm/versions/node/v17.1.0/lib/node_modules/wrangler/wrangler-dist/index_node.js:27064
            throw ex;
            ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:475:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:475:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [
    'https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=redacted&redirect_uri=http%3A%2F%2Flocalhost%3A8976%2Foauth%2Fcallback&scope=account%3Aread%20user%3Aread%20workers%3Awrite%20workers_kv%3Awrite%20workers_routes%3Awrite%20workers_scripts%3Awrite%20workers_tail%3Aread%20zone%3Aread%20offline_access&state=.....'
  ]
}

Node.js v17.1.0
```

**Comment by threepointone** [comment] 2021-11-16 20:16
We definitely want to support environments like github codespaces (and codesandbox, stackblitz, all of them). For one, ee should have a better experience so this doesn't crash immediately like it does. As a workaround, you can start the command with `--local` so it runs fully on the machine itself. That said, you might not be able to automate the opening of devtools either. We'll get better at this. Leaving this issue open until we have a better story.

**Comment by WalshyDev** [comment] 2021-11-20 11:20
Fixing the opening link part is simple, the problem which I'm not sure how should be properly solved is the localhost callback for auth.

What I think is probably easiest is accepting user input to retrieve the callback URL.

Something like:
```
💁 Opening https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=${CLIENT_ID}&redirect_uri=${CALLBACK_URL}&scope=${SCOPES}&state=${STATE}

Failed to launch browser (spawn xdg-open ENOENT)

Please insert callback URL:
$ http://localhost:8976/oauth/callback?code=${CODE}&scope=${SCOPES}&state=${STATE}
```

Not ideal but would at least support codespaces, servers, etc to authenticate through OAuth.

**Comment by kay-is** [comment] 2022-01-03 13:54
I tried the following command:

    wrangler pages dev --local ./public --watch ./build

I still got the error.

**Comment by petebacondarwin** [comment] 2022-05-23 09:28
Thanks for updating this @huw - I agree, let's close this for now and re-open or create a new issue if further problems come to light.

**Closed by petebacondarwin** 2022-05-23 09:28 UTC
Labels: bug

**Comment by Grunet** [comment] 2023-03-08 04:12
Would it be possible to update docs to mention that the OAuth2 login approach won't work on any remote dev environments?

I tried many of them (Gitpod, Codespaces, Stackblitz, Codeflow, Codesandbox) and was seeing similar issues on all of them. I was about to give up until I found this issue mentioning you can use a long-lived access key instead (which I will try out next).

If the docs already exist I'd love to look at them and see what search terms I was missing in my pursuit of them.

**Comment by Grunet** [comment] 2023-03-08 12:30
I found https://developers.cloudflare.com/workers/wrangler/commands/#using-wrangler-login-on-a-remote-machine but I've yet to get those instructions to work

I'll open up a new issue about this since maybe it's a regression?
