### ISSUE TITLE
Support miniflare mount to dev multiple workers

### ISSUE THREAD

**Issue by bkniffler** [cloudflare/wrangler2#967] opened 2022-05-11 07:20 UTC
### 💡 Feature request

Basically the same as https://miniflare.dev/core/mount, starting dev for multiple workers with a single command.

#### Describe the feature

I find myself developing multiple workers (to replace my API). Being able to spin them all up during dev is very handy.

#### Describe the alternatives

Spinning up all one by one or using miniflare.

**Comment by petebacondarwin** [comment] 2022-05-12 12:58
Duplicate of #273

**Closed by petebacondarwin** 2022-05-12 12:58 UTC
Labels: type: enhancement
