### ISSUE TITLE
🐛 BUG: failed request to cloudflare api

### ISSUE THREAD

**Issue by igorbelikov** [cloudflare/wrangler2#1292] opened 2022-06-18 00:47 UTC
### What version of `Wrangler` are you using?

2.0.14

### What operating system are you using?

Mac

### Describe the Bug

from yesterday after execute `wrangler publish` we see this error (we use workers deploy for nuxt, before everything worked well, there are also no errors in the build, the token did not change)

<img width="924" alt="image" src="https://user-images.githubusercontent.com/6455277/174415582-2bd8fe94-43c0-4d86-8f79-2a02e51ede67.png">

what could be the reason for this?

**Comment by petebacondarwin** [comment] 2022-06-18 11:41
This is usually cause by some code running after the request has completed.
With what version of Wrangler was this working before?
Has anything changed in your Worker code?

**Comment by igorbelikov** [comment] 2022-06-19 23:47
@petebacondarwin, we used with wrangler 2.0.4, now I check with latest and see same error

deploy was failed after simple code change (without installing any package dependencies, just a change of code)

we try to run local and its works good (run `nuxt preview`), maybe I can check this error local?

**Comment by igorbelikov** [comment] 2022-06-20 01:58
problem solved, thanks, it was result of changes in code (now we remove part of code which throw error in deploy, but why is not working I don't understand yet)

Why it's working in `nuxt preview`? But not working in `npx miniflare .output/server/index.mjs --site .output/public`? How I can check its in feature?

**Comment by petebacondarwin** [comment] 2022-06-20 07:33
Hi @igorbelikov - I am glad you found the cause of the error. It is hard to guess why your code fails in one case but not in another without seeing it.
But remember that `nuxt preview` is running in node.js, right? While miniflare (and Cloudflare Workers themselves) is a different JavaScript environment which does not support long running instances - hence the error that you cannot trigger certain types of async code outside of a request handler.

This is not an issue with Wrangler so I am going to close this issue. You might be able to find some more support with your problem in our Discord server.

**Closed by petebacondarwin** 2022-06-20 07:33 UTC
Labels: needs reproduction, bug
