### ISSUE TITLE
Error when unrecognized field is used in wrangler.toml

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#497] opened 2022-02-18 21:18 UTC
If an unrecognized field is used in the wrangler.toml, it should throw an error. This is because as we add more features in the future, someone will enviably try to use them on an old version of wrangler; only to find it mysteriously doesn't work.

This has happened a few times with the introduction of `compatibility_date`.

**Comment by petebacondarwin** [comment] 2022-02-19 13:47
This is really a duplicate of https://github.com/cloudflare/wrangler2/issues/291, although I appreciate that the issue doesn't tell you very much. Perhaps move this specific information from here to that issue and close this one?

**Comment by petebacondarwin** [comment] 2022-03-14 21:42
We now do warn in most cases if there are unexpected properties. For example:

https://github.com/cloudflare/wrangler2/blob/7d4ea4342947128eb156a58da69dd008d504103b/packages/wrangler/src/config/validation.ts#L150-L155

**Closed** 2022-03-14 21:43 UTC
Labels: polish

**Comment by threepointone** [comment] 2022-03-15 03:53
Did we add an exception for `miniflare` here?

**Comment by petebacondarwin** [comment] 2022-03-15 06:58
> Did we add an exception for `miniflare` here?

Ah, no. But it is only a warning so it won't actually break.
I'll add that.
